/***************************************************************************//**
* \file IMG_CLASS_tflm_x_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the IMG_CLASS model in float representation.
* Date: 2023-11-05 17:34:24.303405
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef IMG_CLASS_TFLM_X_DATA_FLOAT_H
#define IMG_CLASS_TFLM_X_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t IMG_CLASS_x_data_bin[];
#define IMG_CLASS_X_DATA_BIN_LEN (3136016)

#endif // IMG_CLASS_TFLM_X_DATA_FLOAT_H

