/***************************************************************************//**
* \file MNIST_tflm_x_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the MNIST model in float representation.
* Date: 2023-11-12 08:23:43.431792
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MNIST_TFLM_X_DATA_FLOAT_H
#define MNIST_TFLM_X_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t MNIST_x_data_bin[];
#define MNIST_X_DATA_BIN_LEN (3136016)

#endif // MNIST_TFLM_X_DATA_FLOAT_H

