/***************************************************************************//**
* \file MNIST_tflm_x_data_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the MNIST model in int8x8 representation.
* Date: 2023-11-12 08:23:43.683100
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MNIST_TFLM_X_DATA_INT8X8_H
#define MNIST_TFLM_X_DATA_INT8X8_H

#include <stdint.h>


extern const uint8_t MNIST_x_data_bin[];
#define MNIST_X_DATA_BIN_LEN (784016)

#endif // MNIST_TFLM_X_DATA_INT8X8_H

