/***************************************************************************//**
* \file IMG_CLASS_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains IMG_CLASS model data.
* Date: 2023-11-19 07:22:21.303718
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef IMG_CLASS_TFLM_MODEL_INT8X8_H
#define IMG_CLASS_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t IMG_CLASS_model_bin[];
#else
extern uint8_t IMG_CLASS_model_bin[];
#endif // CY_ML_MODEL_MEM
#define IMG_CLASS_MODEL_BIN_LEN (76248u)
#define IMG_CLASS_ARENA_SIZE (190721u)

#endif // IMG_CLASS_TFLM_MODEL_INT8X8_H

