/***************************************************************************//**
* \file MNIST_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains MNIST model data.
* Date: 2023-11-12 08:23:42.362851
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MNIST_TFLM_MODEL_INT8X8_H
#define MNIST_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t MNIST_model_bin[];
#else
extern uint8_t MNIST_model_bin[];
#endif // CY_ML_MODEL_MEM
#define MNIST_MODEL_BIN_LEN (40448u)
#define MNIST_ARENA_SIZE (33121u)

#endif // MNIST_TFLM_MODEL_INT8X8_H

